export var ProductShoe = [
    {
        id: 1,
        idType: 1,
        star: 4,
        img: "shoe11.jpg",
        color: "Light Grey",
        name: "Grey Tech Runner Sneakers",
        price: 567,
        trademark: "THOM-BROWNE",
        discout: 10,
        description: "Low-top panelled calfskin suede, mesh, and buffed goatskin sneakers in grey. Serrated detailing throughout. Round toe. Lace-up closure in white. Textile logo patch in white at padded tongue. Padded collar. Signature tricolor grosgrain pull-loop at heel collar. Leather lining. Rubber midsole in white and grey featuring signature tricolor stripes and logo embossed at outer side. Treaded rubber outsole in off-white."
    },
    {
        id: 2,
        idType: 1,
        star: 4,
        img: "shoe12.jpg",
        color: "Black",
        name: "Black Leather Longwing Sneaker Brogues",
        price: 675,
        trademark: "THOM-BROWNE",
        discout: 20,
        description:"Grained and panelled leather sneakers in black. Perforated and serrated detailing throughout. Round rubber cap toe in white. Tonal lace-up closure. Signature tricolor grosgrain pull-loop at heel collar. Tonal rubberized logo embossed at heel. Buffed leather lining in tan. Rubberized midsole in white. Treaded gum rubber outsole."
        
    },
    {
        id: 3,
        idType: 1,
        star: 4,
        img: "shoe13.jpg",
        color: "White",
        name: "White Vulcanized Calfskin Sneakers",
        price: 550,
        trademark: "THOM-BROWNE",
        discout: 30,
        description:"Low-top buffed calfskin sneakers in white. Suede trim in grey at round toe. Velcro straps at vamp. Logo patch at padded tongue. Tricolor striped webbing pull-loop and grey suede trim at padded collar. Signature tricolor stripes at welt. Tonal rubber sole featuring embossed logo at heel. Silver-tone hardware."
    },
    {
        id: 4,
        idType: 1,
        star: 5,
        img: "shoe14.jpg",
        color: "White",
        name: "White Vulcanized Brogued Sneakers",
        price: 670,
        trademark: "THOM-BROWNE",
        discout: 10,
        description:"Low-top canvas sneakers in white. Serrated and perforated pebble grained leather trim throughout. Tonal textured rubber trim at round toe. Tonal lace-up closure. Logo patch at tongue. Signature tricolor striped webbing trim at sides. Tricolor striped webbing pull-loop at heel collar. Tonal rubber midsole featuring embossed logo at heel. Treaded crepe rubber sole in brown. Multicolor hardware."
    },
    {
        id: 5,
        idType: 1,
        star: 4,
        img: "shoe15.jpg",
        color: "White",
        name: "White Vulcanized 4-Bar High-Top Sneakers",
        price: 470,
        trademark: "THOM-BROWNE",
        discout: 10,
        description:"High-top canvas sneakers in white. Textured round rubber cap toe. Tonal lace-up closure. Tonal textile logo patch at outer side. Signature tricolor striped grosgrain pull-loop at heel collar. Tonal textured rubber trim at heel counter. Tonal rubber midsole featuring embossed logo at heel. Treaded rubber outsole brown. Multicolor hardware."
    },
    {
        id: 6,
        idType: 1,
        star: 5,
        img: "shoe16.jpg",
        color: "Black/White",
        name: "Black & White Houndstooth Chelsea",
        price: 870,
        trademark: "THOM-BROWNE",
        discout: 40,
        description:"Ankle-high canvas-coated leather Chelsea boots featuring houndstooth pattern in black and white. Almond toe. Elasticized gusset at sides. Signature tricolor grosgrain pull-loop at heel collar. Stacked leather midsole in black. Treaded crepe rubber outsole in black."
    },
    {
        id: 7,
        idType: 2,
        star: 4,
        img: "shoe21.jpg",
        color: "Black/Off-White",
        name: "Black & Off-White Original Achilles Sneakers",
        price: 468,
        trademark: "COMMON PROJECTS",
        discout: 50,
        description:"Low-top patent leather sneakers in black. Round toe. Tonal lace-up closure. Padded tongue. Padded collar with piping in off-white. Signature series number stamp in gold-tone at outer heel. Treaded rubber sole in white."
    },
    {
        id: 8,
        idType: 2,
        star: 4,
        img: "shoe22.jpg",
        color: "White/Navy",
        name: "White & Navy Retro G Sneakers",
        price: 540,
        trademark: "COMMON PROJECTS",
        discout: 40,
        description:"Low top suede and perforated leather sneakers in white and navy. Round toe. Lace-up closure in off-white. Padded tongue. Padded heel collar. Buffed leather heel tab in silver-tone. Signature series number stamp in gold-tone at outer heel. Rubber midsole in off-white. Treaded rubber sole in black."
    },
    {
        id: 9,
        idType: 2,
        star: 4,
        img: "shoe23.jpg",
        color: "White",
        name: "White & Black Retro Sneakers",
        price: 465,
        trademark: "COMMON PROJECTS",
        discout: 30,
        description:"Low-top buffed leather sneakers in white. Round toe. Tonal lace-up closure. Padded tongue and collar. Buffed leather heel tab in black. Logo stamp in gold-tone at outer sides. Tonal treaded rubber sole."
    },
    {
        id: 10,
        idType: 2,
        star: 4,
        img: "shoe24.jpg",
        color: "White/Grey",
        name: "White & Grey Cross Trainer Sneakers",
        price: 468,
        trademark: "COMMON PROJECTS",
        discout: 50,
        description:"Low-top panelled buffed leather and suede sneakers in white and grey. Round toe. Lace-up closure in white. Padded tongue and collar. Logo stamp in gold-tone at outer sides. Treaded rubber sole in white."
    },
    {
        id: 11,
        idType: 2,
        star: 4,
        img: "shoe25.jpg",
        color: "Black/Off-White",
        name: "Black & White Cross Trainer Sneakers",
        price: 478,
        trademark: "COMMON PROJECTS",
        discout: 20,
        description:"Low-top panelled buffed leather sneakers in black and white. Round toe. Lace-up closure in black. Padded tongue and collar. Logo stamp in gold-tone at outer sides. Treaded rubber sole in white."
    },
    {
        id: 12,
        idType: 3,
        star: 4,
        img: "shoe31.jpg",
        color: "Grey",
        name: "Grey Made In US 990 v5 Sneakers",
        price: 358,
        trademark: "NEW BALANCE",
        discout: 15,
        description:"Low-top paneled suede and mesh sneakers in grey. Reflective trim in silver-tone and tonal rubberized trim throughout. Round toe. Lace-up closure in white. Enamelled logo in silver-tone at padded tongue. Padded collar. Logo printed at heel. Logo appliqué in silver-tone at sides. ENCAP® foam rubber midsole in grey and white. Treaded Ndurance™ rubber outsole in black."

    },
    {
        id: 13,
        idType: 3,
        star: 4,
        img: "shoe32.jpg",
        color: "Black",
        name: "Black Made In US 992 Sneakers",
        price: 268,
        trademark: "NEW BALANCE",
        discout: 15,
        description:"Low-top paneled suede and mesh sneakers in black. Reflective silver-tone trim throughout. Round toe. Lace-up closure. Embroidered logo at padded tongue. Padded collar. Reflective logo appliqué at sides. Embroidered logo at heel counter. Signature ABZORB® foam rubber midsole colorblocked in white and grey. Signature treaded Ndurance™ rubber outsole in black."
    },
    {
        id: 14,
        idType: 3,
        star: 4,
        img: "shoe33.jpg",
        color: "Black/Gray",
        name: "Black 574 Core Sneakers",
        price: 168,
        trademark: "NEW BALANCE",
        discout: 30,
        description:"Low-top panelled suede and mesh sneakers in black. Round toe. Lace-up closure in grey. Logo patch at padded tongue. Grey suede trim at padded collar. Leather logo patch in black and grey at outer side. Logo printed in black at grey buffed leather heel tab. Rubber trim at heel counter featuring embossed logo. Foam rubber midsole colorblocked in white and grey. Tonal treaded rubber outsole."
    },
    {
        id: 15,
        idType: 3,
        star: 4,
        img: "shoe34.jpg",
        color: "Black",
        name: "Black Made In US 990 v5 Sneakers",
        price: 158,
        trademark: "NEW BALANCE",
        discout: 35,
        description:"Low-top panelled suede and mesh sneakers in black. Round toe. Lace-up closure. Enamelled logo in silver-tone at padded tongue. Padded collar. Logos printed at heel. Logo appliqué in silver-tone at sides. ENCAP® foam rubber midsole in grey. Treaded Ndurance™ rubber outsole in black."
    },
    {
        id: 16,
        idType: 3,
        star: 4,
        img: "shoe35.jpg",
        color: "Blue/Grey",
        name: "Blue & Grey Made In UK 920 Sneakers",
        price: 230,
        trademark: "NEW BALANCE",
        discout: 30,
        description:"Low-top panelled suede, nubuck, and mesh sneakers in grey, white, blue, and black. Round toe. Lace-up closure in white. Embroidered logo in black at padded tongue. Padded collar. Logo embroidered in white at buffed leather heel tab in burgundy. Logo embroidered in white and logo-embossed rubberized trim in silver-tone at heel. Logo appliqué in blue and silver-tone at sides. OrthoLite® cushioned insole. ENCAP® foam rubber midsole in grey and white. Treaded Ndurance™ rubber outsole in grey and black."
    },
    {
        id: 17,
        idType: 3,
        star: 4,
        img: "shoe36.jpg",
        color: "Black/Silver",
        name: "Black & Silver 997H Sneakers",
        price: 278,
        trademark: "NEW BALANCE",
        discout: 20,
        description:"Low-top panelled mesh and textile sneakers in black and silver-tone. Round toe. Tonal lace-up closure. Reflective textile logo patch at padded tongue. Padded collar. Pull-loop at heel tab. Silver logo stamp at heel counter. Rubberized logo patch at sides. Foam rubber midsole in white. Rubber outsole in white and grey."
    },
    {
        id: 18,
        idType: 3,
        star: 4,
        img: "shoe37.jpg",
        color: "White/Silver",
        name: "White & Silver 997H Sneakers",
        price: 278,
        trademark: "NEW BALANCE",
        discout: 20,
        description:"Low-top paneled mesh and textile sneakers in white and reflective silver-tone. Round toe. Tonal lace-up closure. Textile logo patch at padded tongue. Padded collar. Pull-loop at heel collar. Rubberized logo patch at sides. Silver-tone logo stamp at heel counter. Tonal foam rubber midsole. Treaded rubber outsole in white and grey."
    },
    // nhóm 4
    {
        id: 19,
        idType: 4,
        star: 4,
        img: "shoe41.jpg",
        color: "Black",
        name: "Black Slingback Ballerina Flats",
        price: 400,
        trademark: "TOGA PULLA",
        discout: 30,
        description:"Buffed leather ballerina flats in black. Tonal topstitching at pointed toe. Elasticized slingback strap. Khaki and black croc-embossed leather trim at sides. Signature engraved plaque at stacked leather block heel. Leather sole. Silver-tone hardware. Approx. 1 heel."
    },
    {
        id: 20,
        idType: 4,
        star: 4,
        img: "shoe43.jpg",
        color: "Black",
        name: "Black Faux-Fur Brogues",
        price: 380,
        trademark: "TOGA PULLA",
        discout: 20,
        description:"Polished leather oxfords in black. Pointed toe. Twin adjustable pin-buckle straps at vamp. Serrated detailing at welt. Stacked leather block heel. Leather sole in black. Engraved silver-tone hardware. Approx. 1"
    },
    {
        id: 21,
        idType: 4,
        star: 4,
        img: "shoe44.jpg",
        color: "Black",
        name: "Black Two Buckle Western Boots",
        price: 540,
        trademark: "TOGA PULLA",
        discout: 20,
        description:"Grained leather brogues in black. Serrated and perforated detailing throughout. Round toe. Tonal detachable faux-fur trim at vamp. Lace-up closure featuring engraved hardware at eyerows. Leather lining. Stacked leather heel. Tonal leather sole. Engraved silver-tone hardware. "
    },
    {
        id: 22,
        idType: 4,
        star: 4,
        img: "shoe45.jpg",
        color: "Black",
        name: "Black Heel Hardware Boots",
        price: 490,
        trademark: "TOGA PULLA",
        discout: 10,
        description:"Grained leather brogues in black. Serrated and perforated detailing throughout. Round toe. Tonal detachable faux-fur trim at vamp. Lace-up closure featuring engraved hardware at eyerows. Leather lining. Stacked leather heel. Tonal leather sole. Engraved silver-tone hardware. "
    },
    {
        id: 23,
        idType: 4,
        star: 4,
        img: "shoe46.jpg",
        color: "Black",
        name: "Black Buckle Ballerina Flats",
        price: 395,
        trademark: "TOGA PULLA",
        discout: 0
,
description:"Grained leather brogues in black. Serrated and perforated detailing throughout. Round toe. Tonal detachable faux-fur trim at vamp. Lace-up closure featuring engraved hardware at eyerows. Leather lining. Stacked leather heel. Tonal leather sole. Engraved silver-tone hardware. "    },
    // Nhom 5
    {
        id: 24,
        idType: 5,
        star: 4,
        img: "shoe51.jpg",
        color: "Ice",
        name: "White & Pink Valentino Garavani Fuzzy VLogo Sneakers",
        price: 620,
        trademark: "VALENTINO",
        discout: 20,
        description:"Grained leather brogues in black. Serrated and perforated detailing throughout. Round toe. Tonal detachable faux-fur trim at vamp. Lace-up closure featuring engraved hardware at eyerows. Leather lining. Stacked leather heel. Tonal leather sole. Engraved silver-tone hardware. "
    },
    {
        id: 25,
        idType: 5,
        star: 4,
        img: "shoe52.jpg",
        color: "White/Black",
        name: "White Valentino Garavani Elastic Low-Top Sneakers",
        price: 660,
        trademark: "VALENTINO",
        discout: 20,
        description:"Grained leather brogues in black. Serrated and perforated detailing throughout. Round toe. Tonal detachable faux-fur trim at vamp. Lace-up closure featuring engraved hardware at eyerows. Leather lining. Stacked leather heel. Tonal leather sole. Engraved silver-tone hardware. "
    },
    {
        id: 26,
        idType: 5,
        star: 4,
        img: "shoe53.jpg",
        color: "White/Black",
        name: "White Valentino Garavani VLogo",
        price: 690,
        trademark: "VALENTINO",
        discout: 20,
        description:"Grained leather brogues in black. Serrated and perforated detailing throughout. Round toe. Tonal detachable faux-fur trim at vamp. Lace-up closure featuring engraved hardware at eyerows. Leather lining. Stacked leather heel. Tonal leather sole. Engraved silver-tone hardware. "
    },
    {
        id: 27,
        idType: 5,
        star: 4,
        img: "shoe54.jpg",
        color: "White",
        name: "White Valentino Garavani VLTN Sneakers",
        price: 625,
        trademark: "VALENTINO",
        discout: 10,
        description:"Grained leather brogues in black. Serrated and perforated detailing throughout. Round toe. Tonal detachable faux-fur trim at vamp. Lace-up closure featuring engraved hardware at eyerows. Leather lining. Stacked leather heel. Tonal leather sole. Engraved silver-tone hardware. "
    },
    {
        id: 28,
        idType: 5,
        star: 4,
        img: "shoe55.jpg",
        color: "Black",
        name: "Black & Navy Valentino Garavani",
        price: 670,
        trademark: "VALENTINO",
        discout: 10,
        description:"Grained leather brogues in black. Serrated and perforated detailing throughout. Round toe. Tonal detachable faux-fur trim at vamp. Lace-up closure featuring engraved hardware at eyerows. Leather lining. Stacked leather heel. Tonal leather sole. Engraved silver-tone hardware. "
    },
    {
        id: 29,
        idType: 5,
        star: 4,
        img: "shoe56.jpg",
        color: "White/red",
        name: "White Valentino Garavani Climbers VLogo Sneakers",
        price: 720,
        trademark: "VALENTINO",
        discout: 20,
        description:"Grained leather brogues in black. Serrated and perforated detailing throughout. Round toe. Tonal detachable faux-fur trim at vamp. Lace-up closure featuring engraved hardware at eyerows. Leather lining. Stacked leather heel. Tonal leather sole. Engraved silver-tone hardware. "
    },
    {
        id: 30,
        idType: 5,
        star: 4,
        img: "shoe57.jpg",
        color: "Black",
        name: "Black Valentino Garavani VLogo Sneakers",
        price:760,
        trademark: "VALENTINO",
        discout: 20,
        description:"Grained leather brogues in black. Serrated and perforated detailing throughout. Round toe. Tonal detachable faux-fur trim at vamp. Lace-up closure featuring engraved hardware at eyerows. Leather lining. Stacked leather heel. Tonal leather sole. Engraved silver-tone hardware. "
    },
    {
        id: 31,
        idType: 5,
        star: 4,
        img: "shoe58.jpg",
        color: "Black",
        name: "Black Valentino Garavani Gumboy",
        price: 675,
        trademark: "VALENTINO",
        discout: 20,
        description:"Grained leather brogues in black. Serrated and perforated detailing throughout. Round toe. Tonal detachable faux-fur trim at vamp. Lace-up closure featuring engraved hardware at eyerows. Leather lining. Stacked leather heel. Tonal leather sole. Engraved silver-tone hardware. "
    },
    {
        id: 32,
        idType: 5,
        star: 4,
        img: "shoe59.jpg",
        color: "White",
        name: "White Valentino Garavani Emilio Villalba Edition 'VLTN' Giggies High-Top",
        price: 725,
        trademark: "VALENTINO",
        discout: 10,
        description:"Grained leather brogues in black. Serrated and perforated detailing throughout. Round toe. Tonal detachable faux-fur trim at vamp. Lace-up closure featuring engraved hardware at eyerows. Leather lining. Stacked leather heel. Tonal leather sole. Engraved silver-tone hardware. "
    },
    //NHom 6
    {
        id: 33,
        idType: 6,
        star: 4,
        img: "shoe61.jpg",
        color: "Iron Grey/Dark Smoke",
        name: "Black & Grey Air Max 90 Sneakers",
        price: 425,
        trademark: "NIKE",
        discout: 10,
        description:"Grained leather brogues in black. Serrated and perforated detailing throughout. Round toe. Tonal detachable faux-fur trim at vamp. Lace-up closure featuring engraved hardware at eyerows. Leather lining. Stacked leather heel. Tonal leather sole. Engraved silver-tone hardware. "
    },
    {
        id: 34,
        idType: 6,
        star: 4,
        img: "shoe62.jpg",
        color: "Sail/Gym red",
        name: "Off-White & Red Killshot OG SP",
        price: 225,
        trademark: "NIKE",
        discout: 10,
        description:"Grained leather brogues in black. Serrated and perforated detailing throughout. Round toe. Tonal detachable faux-fur trim at vamp. Lace-up closure featuring engraved hardware at eyerows. Leather lining. Stacked leather heel. Tonal leather sole. Engraved silver-tone hardware. "
    },
    {
        id: 35,
        idType: 6,
        star: 4,
        img: "shoe63.jpg",
        color: "White/University red/White",
        name: "White N.354 Drop-Type HBR Sneakers",
        price: 425,
        trademark: "NIKE",
        discout: 10,
        description:"Grained leather brogues in black. Serrated and perforated detailing throughout. Round toe. Tonal detachable faux-fur trim at vamp. Lace-up closure featuring engraved hardware at eyerows. Leather lining. Stacked leather heel. Tonal leather sole. Engraved silver-tone hardware. "
    },
    {
        id: 36,
        idType: 6,
        star: 4,
        img: "shoe64.jpg",
        color: "Blue/White",
        name: "Blue Killshot SP Sneakers",
        price: 325,
        trademark: "NIKE",
        discout: 10,
        description:"Grained leather brogues in black. Serrated and perforated detailing throughout. Round toe. Tonal detachable faux-fur trim at vamp. Lace-up closure featuring engraved hardware at eyerows. Leather lining. Stacked leather heel. Tonal leather sole. Engraved silver-tone hardware. "
    },
    {
        id: 37,
        idType: 6,
        star: 4,
        img: "shoe65.jpg",
        color: "Teal tint/Midnight navy",
        name: "Blue & Grey Daybreak SP Sneakers",
        price: 225,
        trademark: "NIKE",
        discout: 10,
        description:"Grained leather brogues in black. Serrated and perforated detailing throughout. Round toe. Tonal detachable faux-fur trim at vamp. Lace-up closure featuring engraved hardware at eyerows. Leather lining. Stacked leather heel. Tonal leather sole. Engraved silver-tone hardware. "
    },
    {
        id: 38,
        idType: 6,
        star: 4,
        img: "shoe66.jpg",
        color: "Midnight navy/White",
        name: "Navy & White Air Force 1 '07 Sneakers",
        price: 125,
        trademark: "NIKE",
        discout: 10,
        description:"Grained leather brogues in black. Serrated and perforated detailing throughout. Round toe. Tonal detachable faux-fur trim at vamp. Lace-up closure featuring engraved hardware at eyerows. Leather lining. Stacked leather heel. Tonal leather sole. Engraved silver-tone hardware. "
    },
    {
        id: 39,
        idType: 6,
        star: 4,
        img: "shoe67.jpg",
        color: "White/Black",
        name: "White & Black Air Max 270 React",
        price: 225,
        trademark: "NIKE",
        discout: 10,
        description:"Grained leather brogues in black. Serrated and perforated detailing throughout. Round toe. Tonal detachable faux-fur trim at vamp. Lace-up closure featuring engraved hardware at eyerows. Leather lining. Stacked leather heel. Tonal leather sole. Engraved silver-tone hardware. "
    },
    //Nhom 7
    {
        id: 40,
        idType: 7,
        star: 4,
        img: "shoe71.jpg",
        color: "textile, rubber",
        name: "Black Sorrento Sneakers",
        price: 325,
        trademark: "DOLCE & GABBANA",
        discout: 10,
        description:"Grained leather brogues in black. Serrated and perforated detailing throughout. Round toe. Tonal detachable faux-fur trim at vamp. Lace-up closure featuring engraved hardware at eyerows. Leather lining. Stacked leather heel. Tonal leather sole. Engraved silver-tone hardware. "
    },
    {
        id: 41,
        idType: 7,
        star: 5,
        img: "shoe72.jpg",
        color: "White/Black",
        name: "White & Black Logo Portofino Sneakers",
        price: 225,
        trademark: "DOLCE & GABBANA",
        discout: 10,
        description:"Grained leather brogues in black. Serrated and perforated detailing throughout. Round toe. Tonal detachable faux-fur trim at vamp. Lace-up closure featuring engraved hardware at eyerows. Leather lining. Stacked leather heel. Tonal leather sole. Engraved silver-tone hardware. "
    },
    {
        id: 42,
        idType: 7,
        star: 4,
        img: "shoe73.jpg",
        color: "White/Pink",
        name: "White Daymaster Sneakers",
        price: 265,
        trademark: "DOLCE & GABBANA",
        discout: 10,
        description:"Grained leather brogues in black. Serrated and perforated detailing throughout. Round toe. Tonal detachable faux-fur trim at vamp. Lace-up closure featuring engraved hardware at eyerows. Leather lining. Stacked leather heel. Tonal leather sole. Engraved silver-tone hardware. "
    },
    {
        id: 43,
        idType: 7,
        star: 4,
        img: "shoe74.jpg",
        color: "White/Black",
        name: "White & Black Daymaster Sneakers",
        price: 125,
        trademark: "DOLCE & GABBANA",
        discout: 10,
        description:"Grained leather brogues in black. Serrated and perforated detailing throughout. Round toe. Tonal detachable faux-fur trim at vamp. Lace-up closure featuring engraved hardware at eyerows. Leather lining. Stacked leather heel. Tonal leather sole. Engraved silver-tone hardware. "
    },
    {
        id: 44,
        idType: 7,
        star: 4,
        img: "shoe75.jpg",
        color: "White",
        name: "White & Gold Crest Portofino Sneakers",
        price: 625,
        trademark: "DOLCE & GABBANA",
        discout: 10,
        description:"Grained leather brogues in black. Serrated and perforated detailing throughout. Round toe. Tonal detachable faux-fur trim at vamp. Lace-up closure featuring engraved hardware at eyerows. Leather lining. Stacked leather heel. Tonal leather sole. Engraved silver-tone hardware. "
    },
    {
        id: 45,
        idType: 7,
        star: 4,
        img: "shoe76.jpg",
        color: "Black",
        name: "Black Lace NS1 Sneakers",
        price: 825,
        trademark: "DOLCE & GABBANA",
        discout: 10,
        description:"Grained leather brogues in black. Serrated and perforated detailing throughout. Round toe. Tonal detachable faux-fur trim at vamp. Lace-up closure featuring engraved hardware at eyerows. Leather lining. Stacked leather heel. Tonal leather sole. Engraved silver-tone hardware. "
    },
    {
        id: 46,
        idType: 7,
        star: 4,
        img: "shoe77.jpg",
        color: "White/Black",
        name: "White Insert Portofino Sneakers",
        price: 325,
        trademark: "DOLCE & GABBANA",
        discout: 10,
        description:"Grained leather brogues in black. Serrated and perforated detailing throughout. Round toe. Tonal detachable faux-fur trim at vamp. Lace-up closure featuring engraved hardware at eyerows. Leather lining. Stacked leather heel. Tonal leather sole. Engraved silver-tone hardware. "
    },
    //Nhom 8
]


  