export var VALENTINO = [
    {
        id: 24,
        idType: 5,
        star: 4,
        img: "shoe51.jpg",
        color: "Ice",
        name: "White & Pink Valentino Garavani Fuzzy VLogo Sneakers",
        price: 620,
        trademark: "VALENTINO",
        discout: 20,
        description:"Grained leather brogues in black. Serrated and perforated detailing throughout. Round toe. Tonal detachable faux-fur trim at vamp. Lace-up closure featuring engraved hardware at eyerows. Leather lining. Stacked leather heel. Tonal leather sole. Engraved silver-tone hardware. "
    },
    {
        id: 25,
        idType: 5,
        star: 4,
        img: "shoe52.jpg",
        color: "White/Black",
        name: "White Valentino Garavani Elastic Low-Top Sneakers",
        price: 660,
        trademark: "VALENTINO",
        discout: 20,
        description:"Grained leather brogues in black. Serrated and perforated detailing throughout. Round toe. Tonal detachable faux-fur trim at vamp. Lace-up closure featuring engraved hardware at eyerows. Leather lining. Stacked leather heel. Tonal leather sole. Engraved silver-tone hardware. "
    },
    {
        id: 26,
        idType: 5,
        star: 4,
        img: "shoe53.jpg",
        color: "White/Black",
        name: "White Valentino Garavani VLogo",
        price: 690,
        trademark: "VALENTINO",
        discout: 20,
        description:"Grained leather brogues in black. Serrated and perforated detailing throughout. Round toe. Tonal detachable faux-fur trim at vamp. Lace-up closure featuring engraved hardware at eyerows. Leather lining. Stacked leather heel. Tonal leather sole. Engraved silver-tone hardware. "
    },
    {
        id: 27,
        idType: 5,
        star: 4,
        img: "shoe54.jpg",
        color: "White",
        name: "White Valentino Garavani VLTN Sneakers",
        price: 625,
        trademark: "VALENTINO",
        discout: 10,
        description:"Grained leather brogues in black. Serrated and perforated detailing throughout. Round toe. Tonal detachable faux-fur trim at vamp. Lace-up closure featuring engraved hardware at eyerows. Leather lining. Stacked leather heel. Tonal leather sole. Engraved silver-tone hardware. "
    },
    {
        id: 28,
        idType: 5,
        star: 4,
        img: "shoe55.jpg",
        color: "Black",
        name: "Black & Navy Valentino Garavani",
        price: 670,
        trademark: "VALENTINO",
        discout: 10,
        description:"Grained leather brogues in black. Serrated and perforated detailing throughout. Round toe. Tonal detachable faux-fur trim at vamp. Lace-up closure featuring engraved hardware at eyerows. Leather lining. Stacked leather heel. Tonal leather sole. Engraved silver-tone hardware. "
    },
    {
        id: 29,
        idType: 5,
        star: 4,
        img: "shoe56.jpg",
        color: "White/red",
        name: "White Valentino Garavani Climbers VLogo Sneakers",
        price: 720,
        trademark: "VALENTINO",
        discout: 20,
        description:"Grained leather brogues in black. Serrated and perforated detailing throughout. Round toe. Tonal detachable faux-fur trim at vamp. Lace-up closure featuring engraved hardware at eyerows. Leather lining. Stacked leather heel. Tonal leather sole. Engraved silver-tone hardware. "
    },
    {
        id: 30,
        idType: 5,
        star: 4,
        img: "shoe57.jpg",
        color: "Black",
        name: "Black Valentino Garavani VLogo Sneakers",
        price:760,
        trademark: "VALENTINO",
        discout: 20,
        description:"Grained leather brogues in black. Serrated and perforated detailing throughout. Round toe. Tonal detachable faux-fur trim at vamp. Lace-up closure featuring engraved hardware at eyerows. Leather lining. Stacked leather heel. Tonal leather sole. Engraved silver-tone hardware. "
    },
    {
        id: 31,
        idType: 5,
        star: 4,
        img: "shoe58.jpg",
        color: "Black",
        name: "Black Valentino Garavani Gumboy",
        price: 675,
        trademark: "VALENTINO",
        discout: 20,
        description:"Grained leather brogues in black. Serrated and perforated detailing throughout. Round toe. Tonal detachable faux-fur trim at vamp. Lace-up closure featuring engraved hardware at eyerows. Leather lining. Stacked leather heel. Tonal leather sole. Engraved silver-tone hardware. "
    },
    {
        id: 32,
        idType: 5,
        star: 4,
        img: "shoe59.jpg",
        color: "White",
        name: "White Valentino Garavani Emilio ",
        price: 725,
        trademark: "VALENTINO",
        discout: 10,
        description:"Grained leather brogues in black. Serrated and perforated detailing throughout. Round toe. Tonal detachable faux-fur trim at vamp. Lace-up closure featuring engraved hardware at eyerows. Leather lining. Stacked leather heel. Tonal leather sole. Engraved silver-tone hardware. "
    }
]